library(readr)
texte <- read_file("Contrastes3.Rmd")
texte=gsub("## Exemple\n(((([^#]*)\n))*)","## Exemple\n<div class=\"example\">\n**Exemple**\n\\1\n</div>\n\n",texte)
texte=gsub("[ ]{2,}"," ",texte)
texte=gsub("[\n]{3,}","\n\n",texte)
cat(texte,file="Contrastes3.Rmd")
