library(readr)
texte <- read_file("kkk.txt")
texte=gsub("## Ejemplo\n(((([^#]*)\n))*)","## Ejemplo\n<div class=\"example\">\n**Ejemplo**\n\\1\n</div>\n\n",texte)
texte=gsub("[ ]{2,}"," ",texte)
texte=gsub("[\n]{3,}","\n\n",texte)
cat(texte,file="kkk.Rmd")
